name: opam
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-24.04
        ocaml-version:
          - "5.3"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          dune-cache: true
      - name: Install Dune
        run: opam install dune --yes
      - name: Install dependencies
        run: opam install . --deps-only --with-test --yes || echo "No opam file found, skipping"
      - name: Build
        run: opam exec -- dune build
      - name: Run Ulrik
        run: opam exec -- dune exec ulrik library/ulrik/book.ulrik
      - name: Run Mike
        run: opam exec -- dune exec mike library/mike/book.mike
      - name: Run Dan
        run: opam exec -- dune exec dan library/dan/book.dan
